### ISSUE TITLE
A mistake 

### ISSUE THREAD

**Issue by Sun-Gaust** [ingra14m/mipnerf360-pytorch#1]
There is a error detach operation in distoration_loss function
![image](https://github.com/ingra14m/mipnerf360-pytorch/assets/77910134/ac38a935-6ff8-4952-b24a-04f8742c63f3)
The official implement is as follow.
![image](https://github.com/ingra14m/mipnerf360-pytorch/assets/77910134/6672585c-df89-4aad-8331-12c652c851c5)

**Comment by ingra14m** [comment]
wow, tks for pointing that out. I've fixed that bug.

Thank you soooo much!
